import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";


export const metadata = {
  title: "ALLO |DEPANNAGE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-sm scroll-smooth" >
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
